Stablized 1st CLaaS flow with Vitis and Local Deployment of Kernel with F4PGA
os-fpga/1st-CLaaS pull request #80
Opened 2023-10-02 19:57 UTC by Shelby-dotcom

# Description

The pull request is part of project done under GSOC 2023.

Note: Draft version with no local deployment of kernel with F4PGA yet

2023-10-03 01:58 UTC, stevehoover requested changes
Looks good. Just lots of little stuff.

2023-10-03 01:58 UTC, stevehoover commented on doc/GettingStartedF1.md
> +If you face any color depth issue when using Remote Desktop especially with Xilinx Tools (they get blurry and test is none to visible), you can set High Colour to **16 bit**
Is 16-bit enough? I think I've usually used 24. I even though RDP didn't work for me in the past unless I did this.

2023-10-03 01:58 UTC, stevehoover commented on framework/build/Makefile
> +# then we will use SUPPORTED_TARGETS := hw_on_prem  // TODO: Confirm Steve
?? Let's discuss.

2023-10-03 01:58 UTC, stevehoover commented on framework/build/Makefile
> +# TODO: Confirm Steve, Target downgrade order will be  hw_on_prem, hw, hw_emu, hw_on_prem_emu, sw and then sim
Or would we want a separate variable for target system??

2023-10-03 01:58 UTC, stevehoover commented on framework/build/Makefile
> +# TODO: Prebuilt needed for local hw?
I don't like to have partial changes committed to the mainline. Could you organize your plans a bit, create a single comment block describing the plan, and remove individual comments or add references to the block comment?

2023-10-03 01:58 UTC, stevehoover commented on framework/build/Makefile
> +KERNEL_LDCLFLAGS= --connectivity.nk $(KERNEL_NAME):1
How does this line work without a trailing "\"?

2023-10-03 01:58 UTC, stevehoover commented on framework/build/Makefile
> +    --xp param:compiler.preserveHlsOutput=1 \
spaces vs. tab

2023-10-03 01:58 UTC, stevehoover commented on framework/host/hw_kernel.c
> +  printf("file loaded to memory\n");
For debugging.

2023-10-03 01:58 UTC, stevehoover commented on framework/host/hw_kernel.c
> +  cl_uint num_devices;
// Device info returned by cl* calls???

2023-10-03 01:58 UTC, stevehoover commented on framework/host/hw_kernel.c
> +        printf("CL_DEVICE_NAME %s\n", cl_device_name);
Printed here and twice below.

2023-10-03 01:58 UTC, stevehoover commented on framework/host/hw_kernel.c
> +    printf("CL context  %p\n\n", context);
Debugging?

2023-10-03 01:58 UTC, stevehoover commented on framework/host/hw_kernel.c
> +  printf("Initialize platform complete\n");
Based on verbosity?

2023-10-03 01:58 UTC, stevehoover commented on framework/host/hw_kernel.c
> +  printf("INFO: Loading xclbin %s\n", xclbin);
Based on verbosity?

2023-10-03 01:58 UTC, stevehoover commented on framework/host/hw_kernel.c
> +  printf("CL Start create Program\n");
Based on verbosity?

2023-10-03 01:58 UTC, stevehoover commented on framework/host/hw_kernel.c
> +  free(kernelbinary);
Maybe good, but let's answer this question. See what Xilinx examples do.

2023-10-03 01:58 UTC, stevehoover commented on framework/host/hw_kernel.c
> +  printf("CL created kernel");
Based on verbosity?

2023-10-03 01:58 UTC, stevehoover commented on framework/host/hw_kernel.c
> +    printf("Initialize kernel complete\n");
Based on verbosity?

2023-10-03 01:58 UTC, stevehoover commented on framework/host/hw_kernel.c
> +  size_t global[1];
Comments for these.

2023-10-03 01:58 UTC, stevehoover commented on framework/terraform/ec2_instance.tf
> +      values = ["ami-0e178635787eb5e00"]
We stumble over AMI's going missing now and then. Do you remember whether the error message was clear? Probably not much we can do to report a better error since this is up to Terraform.

2023-10-03 20:06 UTC, Shelby-dotcom commented on doc/GettingStartedF1.md
> +If you face any color depth issue when using Remote Desktop especially with Xilinx Tools (they get blurry and test is none to visible), you can set High Colour to **16 bit**
16 bit worked for me actually. I can try with all the colours again and then add which caused the issue.

2023-10-03 20:07 UTC, Shelby-dotcom commented on framework/build/Makefile
> +# TODO: Prebuilt needed for local hw?
Yeah these comments are unnecessary . Let me remove them for now

2023-10-03 20:09 UTC, Shelby-dotcom commented on framework/terraform/ec2_instance.tf
> +      values = ["ami-0e178635787eb5e00"]
The old AMI was removed by AWS

2023-10-03 22:24 UTC, stevehoover commented on framework/terraform/ec2_instance.tf
> +      values = ["ami-0e178635787eb5e00"]
Yeah, I know. I'm just wondering if we should do anything to catch this situation more cleanly. So first, was the problem obvious to you, or did it take you a while to figure it out? If it took a while, is there anything we can do to catch the issue more cleanly?

2023-10-04 19:54 UTC, Shelby-dotcom commented on framework/terraform/ec2_instance.tf
> +      values = ["ami-0e178635787eb5e00"]
The error was thrown by Terraform that it was unable to establish Instance. Yes , it did took a while to figure out what the issue was. You might remember we had to manually create the instance by searching at AWS Marketplace for FPGA Developer Instance. 
Then searching for its AMI ID was a headache. So yeah , let me know how should i document so it doesn't bother in future

2023-10-04 21:38 UTC, stevehoover commented on framework/terraform/ec2_instance.tf
> +      values = ["ami-0e178635787eb5e00"]
I'm more interested in a better error message than docs. Since it is Terraform that is using this it might be tricky to add a better check. Maybe there's a place within Terraform to add a command that will test this instance and report an error??

2023-10-04 21:39 UTC, stevehoover commented on framework/terraform/ec2_instance.tf
> +      values = ["ami-0e178635787eb5e00"]
Worst-case, just add a "TODO" where this AMI is used in the Terraform file.

2023-10-09 20:11 UTC, Shelby-dotcom commented on framework/build/Makefile
> +KERNEL_LDCLFLAGS= --connectivity.nk $(KERNEL_NAME):1
I have corrected it. It was a mistake. It didn't throw error when doing hw_emu

2023-10-09 20:12 UTC, Shelby-dotcom commented on framework/build/Makefile
> +KERNEL_LDCLFLAGS= --connectivity.nk $(KERNEL_NAME):1
Resolve the conversation then?

2023-10-09 20:20 UTC, Shelby-dotcom commented on framework/host/hw_kernel.c
> +  printf("Initialize platform complete\n");
No, should i add check of verbosity for this?

2023-10-09 20:20 UTC, Shelby-dotcom commented on framework/host/hw_kernel.c
> +  free(kernelbinary);
This is what is being done by Xilinx Example

2023-10-09 20:23 UTC, Shelby-dotcom commented on framework/host/hw_kernel.c
> +  size_t global[1];
Added. They are used in update cl call

2023-10-24 18:27 UTC, stevehoover commented on bin/install_verilator
> +  wget -qO- https://github.com/verilator/verilator/archive/refs/tags/v5.016.tar.gz | tar xvz
Just xz.

2023-10-24 18:31 UTC, stevehoover commented on framework/build/Makefile
> +HOST_CFLAGS=$(SW_CFLAGS) -D KERNEL_AVAIL -D FPGA_DEVICE -D OPENCL -I$(XILINX_XRT)/runtime/include/1_2 -D C_KERNEL -D VITIS_PLATFORM=xilinx_aws-vu9p-f1_shell-v04261818_201920_3 -D KERNEL=$(KERNEL_NAME
Hardcoded. (Was: SDX_PLATFORM=$(AWS_PLATFORM))

2023-10-24 18:36 UTC, stevehoover commented on framework/build/launch
> +    fi
else?

2023-10-24 18:38 UTC, stevehoover commented on framework/build/launch
> +    fi
Delete "fi"?

2023-10-24 18:47 UTC, stevehoover commented on framework/host/hw_kernel.c
> +  printf("File loaded to memory\n");
Not just for debugging? Which file?

2023-10-24 18:50 UTC, stevehoover commented on framework/host/hw_kernel.c
> +	      if (fpga == 0)
indentation

2023-10-24 19:05 UTC, stevehoover commented on framework/terraform/ec2_instance.tf
> +#TODO: AWS AMI updated. To find a way that Terraform can check for new AMIs instead of user changing
data "aws_ami" "instance_ami" {
most_recent = true
owners = ["aws-marketplace"]

  filter {
      name   = "name"
      values = ["FPGA Developer AMI*"]
  }

  filter {
      name   = "virtualization-type"
      values = ["hvm"]
  }
}

2023-10-24 19:07 UTC, stevehoover requested changes
-

2023-10-29 06:57 UTC, Shelby-dotcom commented
> Why 200+ commits showing? Probably it was deviated from Steve Hoover/1st-CLaaS a lot because my branch is a fork from that repository @stevehoover any idea regarding this?

Resolved

2023-10-29 16:14 UTC, stevehoover approved these changes

2023-10-29 16:14 UTC, stevehoover commented on doc/GettingStartedF1.md
> +cd ~/src/project_data/repo  # (~/1st-CLaaS is a symbolic link.)
Why did this change?? Was there no "1st-CLaaS" symlink?

2023-10-29 16:14 UTC, stevehoover commented on doc/GettingStartedF1.md
> +cd ~/src/project_data/repo/apps/mandelbrot/build
Same comment.

2023-10-29 16:14 UTC, stevehoover commented on doc/GettingStartedF1.md
> +make ssh INSTANCE_NAME=<name> SSH_CMD="'source src/project_data/repo/vitis_setup && cd /home/centos/src/project_data/repo/apps/mandelbrot/build && make launch PREBUILT=true'"   # TARGET=hw is the def
Same comment.

2023-10-29 16:14 UTC, stevehoover commented on framework/build/launch
> +    fi
This still needs to be addressed. As is, if line 161 evaluates to true, so will 168.

2023-10-29 16:14 UTC, stevehoover commented on framework/host/hw_kernel.c
> +    // Execute the kernel over the entire range of our 1d input data set
It's not clear to me what these do? What is "our 1d input data set"? What's a "work group item? (If this is a well-documented OpenCL thing, it's fine.)

2023-10-29 16:14 UTC, stevehoover commented on framework/host/hw_kernel.c
> +    // Execute the kernel over the entire range of our 1d input data set
Also fix indentation.

2023-10-29 16:14 UTC, stevehoover commented on framework/host/hw_kernel.h
> +  static const int verbosity = 0; // 0: no debug messages; 10: all debug messages.
We should have one place to set verbosity, not independent from the app verbosity.  Just add a TODO comment for now:
// TODO: This should be combined with verbosity from the server_main. Ideally, it would be configurable via the command-line.

2023-10-29 16:19 UTC, merged

2023-10-29 17:24 UTC, Shelby-dotcom commented on framework/host/hw_kernel.h
> +  static const int verbosity = 0; // 0: no debug messages; 10: all debug messages.
Noted . Will be added in the new PR

2023-10-29 17:54 UTC, Shelby-dotcom commented on framework/build/launch
> +    fi
The launch script throws error if i keep the code like this:
```
# Launch host app.
  echo "Launching host application as: $HOST"
  if [[ $HOST_PID == "" ]]
    # Host application launched externally (probably via gdb).
  then
    if [[ $USE_XILINX = "false" ]] && [[ $USE_FPGA = "false" ]]; #Simulation
    then
        $HOST &
    fi
    else if [[ $USE_XILINX = "true" ]] && [[ $USE_FPGA = "false" ]]; # Hardware Emulation
    then
      sudo -- sh -c "source $XILINX_VITIS/settings64.sh; source /opt/xilinx/xrt/setup.sh; source $AWS_FPGA_REPO_DIR/vitis_setup.sh; emconfigutil --nd 1  --platform $AWS_PLATFORM; export XCL_EMULATION_MODE=hw_emu ; export LC_ALL="C"; $HOST" &
    else # Hardware
      sudo -- sh -c "source $XILINX_VITIS/settings64.sh; source /opt/xilinx/xrt/setup.sh; source $AWS_FPGA_REPO_DIR/vitis_setup.sh; source $AWS_FPGA_REPO_DIR/vitis_runtime_setup.sh; export LANG=C; $HOST" &
    fi
    export HOST_PID=$!
  fi
```
Let me know whats the syntax issue with this

2023-10-29 17:55 UTC, Shelby-dotcom commented on doc/GettingStartedF1.md
> +cd ~/src/project_data/repo  # (~/1st-CLaaS is a symbolic link.)
Yes actually on remote server, the repo is arranged like this. There is nothing named 1st-CLaaS

2023-10-29 17:59 UTC, Shelby-dotcom commented on framework/host/hw_kernel.c
> +    // Execute the kernel over the entire range of our 1d input data set
[from the docs page:](https://www.khronos.org/registry/cl/sdk/1.2/docs/man/xhtml/clEnqueueTask.html)

The kernel is executed using a single work-item.

clEnqueueTask is equivalent to calling clEnqueueNDRangeKernel with work_dim = 1, global_work_offset = NULL, global_work_size[0] set to 1, and local_work_size[0] set to 1.

Also explained in https://stackoverflow.com/questions/35487679/using-clenqueuendrangekernel-in-opencl

2023-10-29 20:35 UTC, stevehoover commented on framework/host/hw_kernel.c
> +    // Execute the kernel over the entire range of our 1d input data set
ok. Put that link in a the comment.

2023-10-29 20:38 UTC, stevehoover commented on doc/GettingStartedF1.md
> +cd ~/src/project_data/repo  # (~/1st-CLaaS is a symbolic link.)
Okay. We could add it to the `ln` commands in framework/terraform/ec2_instance.tf.

2023-10-29 20:42 UTC, stevehoover commented on framework/build/launch
> +    fi
if-then-else, not if-then-fi-else.

2023-10-30 19:31 UTC, Shelby-dotcom commented on doc/GettingStartedF1.md
> +cd ~/src/project_data/repo  # (~/1st-CLaaS is a symbolic link.)
Noted